###### POST Mahasiswa
POST http://localhost:5000/mahasiswa
Content-Type: application/json

{
    "name": "Ahmad Zaini Nijar",
    "nim": "243235345",
    "picture": "./images/test.jpeg",
    "major": "Teknik Informatika"
}

###### GET Mahasiswa
GET http://localhost:5000/mahasiswa
Content-Type: application/json

###### UPDATE Mahasiswa
PATCH http://localhost:5000/mahasiswa
Content-Type: application/json

{
    "id": "2",
    "name": "Zaini Nijar",
    "nim": "22101152630093",
    "picture": "./images/test.jpeg",
    "major": "Teknik Informatika"
}

###### DELETE Mahasiswa
DELETE http://localhost:5000/mahasiswa
Content-Type: application/json

{
    "id": "6"
}

###### GET Mahasiswa By ID
GET http://localhost:5000/mahasiswa/93684
Content-Type: application/json
